# Generated by Django 6.1 on 2026-08-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('technician', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_plate', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_parts', models.IntegerField()),
                ('parts_details', models.TextField()),
                ('technician', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WheelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_plate', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('alignment', 'Wheel Alignment'), ('balancing', 'Wheel Balancing'), ('both', 'Both')], max_length=20)),
                ('date', models.DateField()),
                ('technician', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
