# Generated by Django 6.1 on 2026-08-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_partsale_unit_price_alter_servicerecord_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsale',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
