# Generated by Django 6.1 on 2026-08-31 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customer_phone_number'),
        ('services', '0004_alter_partsale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsale',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='car_plate',
        ),
        migrations.RemoveField(
            model_name='wheelservice',
            name='car_plate',
        ),
        migrations.RemoveField(
            model_name='wheelservice',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='partsale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='wheelservice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wheel_services', to='accounts.customer'),
        ),
    ]
