# Generated by hand on 2026-09-01
# Restores car_plate on ServiceRecord and WheelService, which was removed
# in 0005 but is still required by forms.py, views.py, and templates
# throughout the services and dashboard apps.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_partsale_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='car_plate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='wheelservice',
            name='car_plate',
            field=models.CharField(default='', max_length=20),
        ),
    ]
