# Generated by hand on 2026-09-01
# Removes the unused dashboard.Service and dashboard.WheelJob stub models.
# They were empty placeholders (id column only) that duplicated the real
# services.ServiceRecord / services.WheelService models and were never
# fully implemented.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='WheelJob',
        ),
    ]
